Resources:
  ModelSTM:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: modelId
          AttributeType: S
      KeySchema:
        - AttributeName: modelId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        'Fn::Join':
          - '-'
          - - !Ref 'AWS::StackName'
            - ModelSTM

  ModelInstance:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: instanceId
          AttributeType: S
      KeySchema:
        - AttributeName: instanceId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        'Fn::Join':
          - '-'
          - - !Ref 'AWS::StackName'
            - ModelInstance

Outputs:
  STFTableName:
    Value: !Ref ModelSTM
    Export:
      Name: !Sub '${AWS::StackName}-STFTableName'

  InstanceTableName:
    Value: !Ref ModelSTM
    Export:
      Name: !Sub '${AWS::StackName}-InstanceTableName'
